# Generated by Django 4.1.7 on 2023-02-16 13:11

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMachineSetting',
            fields=[
                ('common_machine_setting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio1', models.FileField(blank=True, upload_to='common_audio_settings', validators=[api.validators.validate_audio_file_extension])),
                ('audio2', models.FileField(blank=True, upload_to='common_audio_settings', validators=[api.validators.validate_audio_file_extension])),
                ('audio3', models.FileField(blank=True, upload_to='common_audio_settings', validators=[api.validators.validate_audio_file_extension])),
                ('audio4', models.FileField(blank=True, upload_to='common_audio_settings', validators=[api.validators.validate_audio_file_extension])),
                ('audio5', models.FileField(blank=True, upload_to='common_audio_settings', validators=[api.validators.validate_audio_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('dose_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('j_cm2', models.FloatField()),
                ('tube', models.CharField(choices=[('Tube A', 'Tube A'), ('Tube B', 'Tube B')], max_length=200)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Not Started', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoseComment',
            fields=[
                ('dose_comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('machine_country', models.CharField(blank=True, max_length=50)),
                ('machine_state', models.CharField(blank=True, max_length=50)),
                ('machine_city', models.CharField(blank=True, max_length=50)),
                ('machine_status', models.CharField(blank=True, default='off', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_machine_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.commonmachinesetting')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageComment',
            fields=[
                ('package_comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistoryPhotos',
            fields=[
                ('PatientHistoryPhotos_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, upload_to='patient_history_photos', validators=[api.validators.validate_image_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueMachineSetting',
            fields=[
                ('unique_machine_setting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio6', models.FileField(blank=True, upload_to='machine_audio_settings', validators=[api.validators.validate_audio_file_extension])),
                ('audio6_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('developer', 'developer'), ('operator', 'operator')], default='operater', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('patient_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('thyroid', models.CharField(blank=True, max_length=100)),
                ('auto_imm_dis', models.CharField(blank=True, max_length=100)),
                ('jaundice', models.CharField(blank=True, max_length=100)),
                ('fh_auto_imm_dis', models.CharField(blank=True, max_length=100)),
                ('ophthalmological_problems', models.CharField(blank=True, max_length=100)),
                ('hospitalization', models.CharField(blank=True, max_length=100)),
                ('psychiatric_history', models.CharField(blank=True, max_length=100)),
                ('keloidol_tendency', models.CharField(blank=True, max_length=100)),
                ('epilepsy', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=100)),
                ('steroid_history', models.CharField(blank=True, max_length=100)),
                ('pdf', models.FileField(blank=True, upload_to='pdfs', validators=[api.validators.validate_pdf_file_extension])),
                ('antibodies_to_thyroid', models.CharField(blank=True, max_length=100)),
                ('h_o_epilepsy', models.CharField(blank=True, max_length=100)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('fh_b_vitiligo', models.CharField(blank=True, max_length=100)),
                ('h_o_thyroid', models.CharField(blank=True, max_length=100)),
                ('hb_value', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ManyToManyField(blank=True, to='api.medicine')),
                ('photo_of_date', models.ManyToManyField(blank=True, to='api.patienthistoryphotos')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('patient_type', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('skin_type', models.CharField(blank=True, max_length=200)),
                ('system_code', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='patient_photo', validators=[api.validators.validate_image_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
                ('patient_history_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=200)),
                ('package_status', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_comment', models.ManyToManyField(blank=True, to='api.packagecomment')),
                ('patient_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MachineHardware',
            fields=[
                ('machine_hardware_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default=0, max_length=50)),
                ('j_cm2', models.FloatField(default=0)),
                ('tube', models.CharField(choices=[('Tube A', 'Tube A'), ('Tube B', 'Tube B'), (0, 0)], max_length=200)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Not Started', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dose')),
                ('machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.uniquemachinesetting'),
        ),
        migrations.AddField(
            model_name='dose',
            name='dose_comments',
            field=models.ManyToManyField(blank=True, to='api.dosecomment'),
        ),
        migrations.AddField(
            model_name='dose',
            name='machine_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine'),
        ),
        migrations.AddField(
            model_name='dose',
            name='package_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.package'),
        ),
        migrations.AddField(
            model_name='dose',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.CreateModel(
            name='DoctorViewStorage',
            fields=[
                ('doctor_view_storage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
